@startuml 

class Hombre
class Mujer
class Nombre
class Pareja 
class Usuario
class Opcion 
class Arma 
class Evento 
class Pelea

Usiario "1" o--"3"Opcion 
Hombre o-- Pareja 
Mujer o-- pareja 

@enduml 